#!/usr/bin/env python3.4

from ROOT import TGraphErrors, TFile, TCanvas, kGray, TH2F, TH1F, gDirectory, kRed, kGreen, gStyle, TPad, TLine, TLegend, gPad, TPaveText
from numpy import array
gStyle.SetOptStat(0)
gStyle.SetNumberContours(999)
#gStyle.SetPalette(87)
gStyle.SetPaintTextFormat(".2f")

f_theta_mc = TFile("plots/mc/theta_mcc7.root")
h_theta_mc = gDirectory.Get("h_theta_reco")
h_theta_mc.SetName("h_theta_reco")
h_theta_mc_clone = h_theta_mc.Clone()
h_theta_mc_clone.SetName("h_theta_mc_clone")
e_theta_file = TFile("plots/data/eff_theta_pandoraCosmic.root")
e_theta = gDirectory.Get("h_theta_mucs_clone")
h_theta_mc.SetLineColor(kRed+1)
h_theta_mc_clone.SetFillStyle(3001)
h_theta_mc_clone.SetFillColor(kRed+1)
h_theta_mc_clone.SetLineColor(kRed+1)
f_theta = TFile("plots/data/e_theta_pandoraCosmic.root")
h_theta = gDirectory.Get("h_theta")
h_theta.SetMarkerStyle(20)
h_theta.SetLineColor(1)
f_theta_sys = TFile("plots/data/e_theta_sys_pandoraCosmic.root")
h_theta_sys = gDirectory.Get("h_theta_sys")
h_theta_ratio = h_theta_sys.Clone()
h_theta_ratio.Divide(h_theta_mc)
h_theta_ratio.SetMarkerStyle(20)
h_theta_ratio.SetLineColor(1)
h_theta_ratio.GetYaxis().SetRangeUser(0.91,1.09)
h_theta_ratio.GetYaxis().SetNdivisions(5,0,5)
h_theta_ratio.GetYaxis().SetTitle("Data/MC")
h_theta_ratio.GetYaxis().SetLabelSize(0.12)
h_theta_ratio.GetYaxis().SetTitleSize(0.13)
h_theta_ratio.GetYaxis().SetTitleOffset(0.3)
h_theta_ratio.GetXaxis().SetLabelSize(0.12)
h_theta_ratio.GetXaxis().SetTitleSize(0.13)
h_theta_ratio.GetXaxis().SetTitleOffset(0.85)


theta_bins = array([h_theta.GetBinCenter(i) for i in range(1,h_theta.GetNbinsX()+2)])
theta_values = array([h_theta.GetBinContent(i) for i in range(1,h_theta.GetNbinsX()+2)])
theta_bins_err = array([7.5]*h_theta.GetNbinsX())
theta_stat_err = array([h_theta.GetBinError(i) for i in range(1,h_theta.GetNbinsX()+2)])
theta_sys_err = array([h_theta_sys.GetBinError(i) for i in range(1,h_theta_sys.GetNbinsX()+2)])
g_theta_stat = TGraphErrors(h_theta.GetNbinsX(),theta_bins,theta_values,theta_bins_err,theta_stat_err)
g_theta_sys = TGraphErrors(h_theta.GetNbinsX(),theta_bins,theta_values,theta_bins_err,theta_sys_err)

c_theta = TCanvas("c_theta","")
c_theta.cd()

pad_top = TPad("pad_top","",0, 0.3,1,1)
pad_top.SetBottomMargin(0)
pad_top.Draw()
pad_top.cd()
g_theta_sys.SetMarkerStyle(20)
g_theta_stat.SetFillStyle(3001)
g_theta_stat.SetFillColor(kGray+2)
g_theta_stat.SetLineWidth(2)
g_theta_stat.SetLineColor(kGray+2)
h_theta_mc.SetMarkerStyle(0)
h_theta_mc_clone.SetMarkerStyle(0)
h_theta_mc.Draw("hist")
h_theta_mc.GetYaxis().SetTitle("Efficiency")
x_minbin = h_theta_mc.FindFirstBinAbove()
low = h_theta_mc.GetXaxis().GetBinLowEdge(x_minbin)
x_maxbin = h_theta_mc.FindLastBinAbove()
high = h_theta_mc.GetXaxis().GetBinUpEdge(x_maxbin)
h_theta_mc.GetXaxis().SetRangeUser(low,high)
h_theta_mc.GetYaxis().SetTitleOffset(0.7)
h_theta_mc_clone.Draw("e2same")
g_theta_sys.Draw("P")
#e_theta.Draw("Psame")
g_theta_stat.Draw("2")
pt = TPaveText(0.10,0.905,0.40,0.98, "ndc")
pt.AddText("MicroBooNE in progress")
pt.SetFillColor(0)
pt.SetBorderSize(0)
pt.SetShadowColor(0)
pt.Draw()
leg = TLegend(0.66,0.09,0.86,0.26)
leg.AddEntry(g_theta_sys,"Data - stat. #oplus sys.","ep")
leg.AddEntry(g_theta_stat,"Data - stat. only","f")
leg.AddEntry("h_theta_mc_clone","Monte Carlo","f")
leg.Draw()
c_theta.cd()
pad_bottom = TPad("pad_bottom","",0, 0.02, 1, 0.3)
pad_bottom.SetTopMargin(0)
pad_bottom.SetBottomMargin(0.22)
pad_bottom.Draw()
pad_bottom.cd()

h_theta_ratio.GetXaxis().SetRangeUser(low,high)
h_theta_ratio.Draw("ep")
line1 = TLine(low,1,high,1)
line1.SetLineStyle(2)
line1.SetLineWidth(2)
line1.Draw()

c_theta.Update()

f_phi_mc = TFile("plots/mc/phi_mcc7.root")
h_phi_mc = gDirectory.Get("h_phi_reco")
h_phi_mc_clone = h_phi_mc.Clone()
h_phi_mc.SetLineColor(kRed+1)
h_phi_mc_clone.SetFillStyle(3001)
h_phi_mc_clone.SetFillColor(kRed+1)
f_phi = TFile("plots/data/e_phi_pandoraCosmic.root")
h_phi = gDirectory.Get("h_phi")
h_phi.SetMarkerStyle(20)
h_phi.SetLineColor(1)
f_phi_sys = TFile("plots/data/e_phi_sys_pandoraCosmic.root")
h_phi_sys = gDirectory.Get("h_phi_sys")
h_phi_ratio = h_phi_sys.Clone()
h_phi_ratio.Divide(h_phi_mc)
h_phi_ratio.SetMarkerStyle(20)
h_phi_ratio.SetLineColor(1)
h_phi_ratio.GetYaxis().SetRangeUser(0.91,1.09)
h_phi_ratio.GetYaxis().SetNdivisions(5,0,5)
h_phi_ratio.GetYaxis().SetTitle("Data/MC")
h_phi_ratio.GetYaxis().SetLabelSize(0.12)
h_phi_ratio.GetYaxis().SetTitleSize(0.13)
h_phi_ratio.GetYaxis().SetTitleOffset(0.3)
h_phi_ratio.GetXaxis().SetLabelSize(0.12)
h_phi_ratio.GetXaxis().SetTitleSize(0.13)
h_phi_ratio.GetXaxis().SetTitleOffset(0.85)

phi_bins = array([h_phi.GetBinCenter(i) for i in range(1,h_phi.GetNbinsX()+2)])
phi_values = array([h_phi.GetBinContent(i) for i in range(1,h_phi.GetNbinsX()+2)])
phi_bins_err = array([7.5]*h_phi.GetNbinsX())
phi_stat_err = array([h_phi.GetBinError(i) for i in range(1,h_phi.GetNbinsX()+2)])
phi_sys_err = array([h_phi_sys.GetBinError(i) for i in range(1,h_phi_sys.GetNbinsX()+2)])
g_phi_stat = TGraphErrors(h_phi.GetNbinsX(),phi_bins,phi_values,phi_bins_err,phi_stat_err)
g_phi_sys = TGraphErrors(h_phi.GetNbinsX(),phi_bins,phi_values,phi_bins_err,phi_sys_err)

c_phi = TCanvas("c_phi","")
c_phi.cd()
pad_top = TPad("pad_top","",0, 0.3,1,1)
pad_top.SetBottomMargin(0)
pad_top.Draw()
pad_top.cd()
g_phi_sys.SetMarkerStyle(20)
g_phi_stat.SetFillStyle(3001)
g_phi_stat.SetFillColor(kGray+2)
h_phi_mc.SetMarkerStyle(0)
h_phi_mc_clone.SetMarkerStyle(0)
h_phi_mc.Draw("hist")
h_phi_mc.GetYaxis().SetTitle("Efficiency")
h_phi_mc.SetMarkerStyle(0)
x_minbin = h_phi_mc.FindFirstBinAbove()
low = h_phi_mc.GetXaxis().GetBinLowEdge(x_minbin)
x_maxbin = h_phi_mc.FindLastBinAbove()
high = h_phi_mc.GetXaxis().GetBinUpEdge(x_maxbin)
h_phi_mc.GetXaxis().SetRangeUser(low,high)
h_phi_mc.GetYaxis().SetTitleOffset(0.7)
h_phi_mc_clone.Draw("e2same")
g_phi_sys.Draw("P")
g_phi_stat.Draw("2")
pt.Draw()
leg.Draw()
c_phi.cd()
pad_bottom = TPad("pad_bottom","",0, 0.02, 1, 0.3)
pad_bottom.SetTopMargin(0)
pad_bottom.SetBottomMargin(0.22)
pad_bottom.Draw()
pad_bottom.cd()
h_phi_ratio.GetXaxis().SetRangeUser(low,high)
h_phi_ratio.Draw("ep")
line2 = TLine(low,1,high,1)
line2.SetLineStyle(2)
line2.SetLineWidth(2)
line2.Draw()
c_phi.Update()


f_l_mc = TFile("plots/mc/l_mcc7.root")
h_l_mc = gDirectory.Get("h_l_reco")
h_l_mc_clone = h_l_mc.Clone()
h_l_mc.SetLineColor(kRed+1)
h_l_mc_clone.SetFillStyle(3001)
h_l_mc_clone.SetFillColor(kRed+1)
f_l = TFile("plots/data/e_l_pandoraCosmic.root")
h_l = gDirectory.Get("h_l")
h_l.SetMarkerStyle(20)
h_l.SetLineColor(1)
f_l_sys = TFile("plots/data/e_l_sys_pandoraCosmic.root")
h_l_sys = gDirectory.Get("h_l_sys")

h_l_ratio = h_l_sys.Clone()
h_l_ratio.SetMarkerStyle(20)
h_l_ratio.SetLineColor(1)
h_l_ratio.Divide(h_l_mc)
h_l_ratio.GetYaxis().SetRangeUser(0.91,1.09)
h_l_ratio.GetYaxis().SetNdivisions(5,0,5)
h_l_ratio.GetYaxis().SetTitle("Data/MC")
h_l_ratio.GetYaxis().SetLabelSize(0.12)
h_l_ratio.GetYaxis().SetTitleSize(0.13)
h_l_ratio.GetYaxis().SetTitleOffset(0.3)
h_l_ratio.GetXaxis().SetLabelSize(0.12)
h_l_ratio.GetXaxis().SetTitleSize(0.13)
h_l_ratio.GetXaxis().SetTitleOffset(0.85)


l_bins = array([h_l.GetBinCenter(i) for i in range(1,h_l.GetNbinsX()+2)])
l_values = array([h_l.GetBinContent(i) for i in range(1,h_l.GetNbinsX()+2)])
l_bins_err = array([30.]*5)
l_stat_err = array([h_l.GetBinError(i) for i in range(1,h_l.GetNbinsX()+2)])
l_sys_err = array([h_l_sys.GetBinError(i) for i in range(1,h_l.GetNbinsX()+2)])
g_l_stat = TGraphErrors(h_l.GetNbinsX(),l_bins,l_values,l_bins_err,l_stat_err)
g_l_sys = TGraphErrors(h_l.GetNbinsX(),l_bins,l_values,l_bins_err,l_sys_err)

c_l = TCanvas("c_l","")
c_l.cd()
pad_top = TPad("pad_top","",0, 0.3,1,1)
pad_top.SetBottomMargin(0)
pad_top.Draw()
pad_top.cd()
g_l_sys.SetMarkerStyle(20)
g_l_stat.SetFillStyle(3001)
g_l_stat.SetFillColor(kGray+2)
h_l_mc.SetMarkerStyle(0)
h_l_mc_clone.SetMarkerStyle(0)
h_l_mc.Draw("hist")

h_l_mc.GetYaxis().SetTitle("Efficiency")

x_minbin = h_l_mc.FindFirstBinAbove()
low = h_l_mc.GetXaxis().GetBinLowEdge(x_minbin)
x_maxbin = h_l_mc.FindLastBinAbove()
high = h_l_mc.GetXaxis().GetBinUpEdge(x_maxbin)
h_l_mc.GetXaxis().SetRangeUser(low,high)
h_l_mc.GetYaxis().SetTitleOffset(0.7)
h_l_mc_clone.Draw("e2same")
g_l_stat.Draw("2")
g_l_sys.Draw("P")
pt.Draw()
leg.Draw()

c_l.cd()
pad_bottom = TPad("pad_bottom","",0, 0.02, 1, 0.3)
pad_bottom.SetTopMargin(0)
pad_bottom.SetBottomMargin(0.22)
pad_bottom.Draw()
pad_bottom.cd()
h_l_ratio.GetXaxis().SetRangeUser(low,high)
h_l_ratio.Draw("ep")
line3 = TLine(low,1,high,1)
line3.SetLineStyle(2)
line3.SetLineWidth(2)
line3.Draw()
c_l.Update()

f_theta_phi_mc = TFile("plots/mc/theta_phi_mcc7.root")
h_theta_phi_mc = gDirectory.Get("h_theta_phi_reco")
f_theta_phi = TFile("plots/data/e_theta_phi_pandoraCosmic.root")
h_theta_phi = gDirectory.Get("h_theta_phi")
h_theta_phi.Divide(h_theta_phi_mc)
h_theta_phi.GetZaxis().SetRangeUser(0.5,1.5)
h_theta_phi.GetZaxis().SetTitle("Data/Monte Carlo")
c_theta_phi = TCanvas("c_theta_phi")
h_theta_phi.Draw("colz texte")
h_theta_phi.GetZaxis().RotateTitle()
h_theta_phi.GetXaxis().SetRangeUser(60,120)
h_theta_phi.GetYaxis().SetRangeUser(-90,-45)
pt.Draw()

gPad.SetRightMargin(0.15)
c_theta_phi.Update()

f_theta_l_mc = TFile("plots/mc/theta_l_mcc7.root")
h_theta_l_mc = gDirectory.Get("h_theta_l_reco")
f_theta_l = TFile("plots/data/e_theta_l_pandoraCosmic.root")
h_theta_l = gDirectory.Get("h_theta_l")
h_theta_l.Divide(h_theta_l_mc)
h_theta_l.GetZaxis().SetRangeUser(0.5,1.5)
c_theta_l = TCanvas("c_theta_l")
h_theta_l.Draw("colz texte")
h_theta_l.GetZaxis().SetTitle("Data/Monte Carlo")
h_theta_l.GetZaxis().RotateTitle()
h_theta_l.GetXaxis().SetRangeUser(60,120)
h_theta_l.GetYaxis().SetRangeUser(20,320)
gPad.SetRightMargin(0.15)
pt.Draw()

c_theta_l.Update()

f_phi_l_mc = TFile("plots/mc/phi_l_mcc7.root")
h_phi_l_mc = gDirectory.Get("h_phi_l_reco")
f_phi_l = TFile("plots/data/e_phi_l_pandoraCosmic.root")
h_phi_l = gDirectory.Get("h_phi_l")
h_phi_l.Divide(h_phi_l_mc)
h_phi_l.GetZaxis().SetRangeUser(0.5,1.5)
c_phi_l = TCanvas("c_phi_l")
h_phi_l.Draw("colz texte")
h_phi_l.GetZaxis().SetTitle("Data/Monte Carlo")
h_phi_l.GetZaxis().RotateTitle()
h_phi_l.GetXaxis().SetRangeUser(-90,-45)
h_phi_l.GetYaxis().SetRangeUser(20,320)
gPad.SetRightMargin(0.15)
pt.Draw()

c_phi_l.Update()

# gStyle.SetCanvasPreferGL(1)
# f_theta_phi_l_mc = TFile("plots/mc/theta_phi_l_mcc7.root")
# h_theta_phi_l_mc = gDirectory.Get("h_theta_phi_l_tpc")
# f_theta_phi_l = TFile("e_theta_phi_l_data.root")
# h_theta_phi_l = gDirectory.Get("h_theta_phi_l_tpc")
# h_theta_phi_l.GetZaxis().SetTitleOffset(1.7)
# h_theta_phi_l.GetXaxis().SetTitleOffset(1.7)
# h_theta_phi_l.GetYaxis().SetTitleOffset(1.7)
# h_theta_phi_l.Divide(h_theta_phi_l_mc)
# h_theta_phi_l.GetZaxis().SetRangeUser(20,370)
# h_theta_phi_l.GetXaxis().SetRangeUser(60,120)
# h_theta_phi_l.GetYaxis().SetRangeUser(-90,-40)
# c_theta_phi_l = TCanvas("c_theta_phi_l")
# h_theta_phi_l.Draw("glbox")
# c_theta_phi_l.Update()
input()
